name = "ks/cip102"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'ks/cip102'"

[repository]
user = "ks"
project = "cip102"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
